"""empty message

Revision ID: 67e48a097b7a
Revises: 2d7d57589f10
Create Date: 2020-05-05 07:26:43.280560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67e48a097b7a'
down_revision = '2d7d57589f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wishes_text_key', 'wishes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('wishes_text_key', 'wishes', ['text'])
    # ### end Alembic commands ###
